name: Deploy to FTP

on:
  push:
    branches:
      - main  # Change to your default branch if it's not main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install FTP Deploy Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        protocol: ftps
        local-dir: ./  # The local directory to upload
        server-dir: /public_html/amsaad.com/tms  # The remote directory to upload to
